global:
  scrape_interval:     3s
  external_labels:
      monitor: 'test-app'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['prometheus:9090']

  - job_name: 'exporter'
    static_configs:
        - targets: ['exporter:8000']
