{
 "title": "Example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(number_of_requests_total[1m])",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_usage{resource_type=\"Memory\"}",
     "legendFormat": "mem {{ job }}"
    }
   ]
  },
  {
   "title": "Files smaller than 4MB",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uploaded_image_bytes_bucket{le=\"4.194304e+06\"}",
     "legendFormat": "Value"
    },
    {
     "expr": "uploaded_image_bytes_bucket{le=\"4.194304e+06\"} / ignoring(le) uploaded_image_bytes_count",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "HTTP Requested Urls ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint)(my_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_usage{resource_type=\"CPU\"}",
     "legendFormat": "cpu {{ job }}"
    }
   ]
  },
  {
   "title": "Files larger than 4MB",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uploaded_image_bytes_count - ignoring(le) uploaded_image_bytes_bucket{le=\"4.194304e+06\"}"
    }
   ]
  }
 ]
}